name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: testing, UPSTREAM_WORKSPACE: 'stonefish_ros.rosinstall -stonefish_ros'}
          - {ROS_DISTRO: noetic, ROS_REPO: main, UPSTREAM_WORKSPACE: 'stonefish_ros.rosinstall -stonefish_ros'}
          - {ROS_DISTRO: melodic, ROS_REPO: main, UPSTREAM_WORKSPACE: 'stonefish_ros.rosinstall -stonefish_ros'}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
